# Generated by Django 2.2 on 2021-02-27 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_detail', models.CharField(max_length=100)),
                ('status', models.CharField(db_column='Operation', max_length=5)),
                ('price', models.IntegerField()),
                ('comments', models.CharField(blank=True, max_length=45, null=True)),
                ('created_time', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
            options={
                'db_table': 'sell',
                'managed': True,
                'unique_together': {('sell_id', 'inventory')},
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('buy_id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_date', models.DateField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
            options={
                'db_table': 'buy',
                'managed': True,
                'unique_together': {('buy_id', 'inventory')},
            },
        ),
    ]
