# Generated by Django 2.2 on 2021-02-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created_time',
            field=models.DateField(auto_now=True),
        ),
    ]
