# Generated by Django 2.2 on 2021-01-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='inventory_id',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='sell',
            old_name='inventory_id',
            new_name='inventory',
        ),
        migrations.AlterUniqueTogether(
            name='buy',
            unique_together={('buy_id', 'inventory')},
        ),
        migrations.AlterUniqueTogether(
            name='sell',
            unique_together={('sell_id', 'inventory')},
        ),
    ]
